---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pihole_container_environment:
      TZ="Europe/Madrid"
      DNS1="1.1.1.1"
      DNS2="1.0.0.1"
      WEBPASSWORD="admin"
      ServerIP="127.0.0.1"
      WEB_PORT="8080"

  roles:
    - role: dsegurag.pihole
